def get_buzzwords():
    buzzwords =[
        'Absent',
        'Access',
        'Acqhire',
        'Additionality',
        'Adminispam',
        'Alt-Tab',
        'ASCII Art',
        'ASCII-Armor',
        'Astroturfing',
        'Asyncronous',
        'Attosecond',
        'Automagically',
        'Backronym',
        'Backslash',
        'Banhammer',
        'Beggarware',
        'Bellhead',
        'Betamaxed',
        'BiCapitalization',
        'Bio-Break',
        'Black Hole',
        'Bleeding Edge',
        'Blinkenlights',
        'Bloatware',
        'Blockchain',
        'Blogger',
        'Blogorrhea',
        'Blogosphere',
        'Boilerplate',
        'Bootleg',
        'Botnet',
        'Brogramming',
        'Bug',
        'Bug Bounty',
        'Bulletproof',
        'Burn Rate',
        'Business Driver',
        'Business Logic',
        'Business Rule',
        'Button Masher',
        'Buzzword-Compliant',
        'Cached Out',
        'Carbon Footprint',
        'Carebear',
        'Careware',
        'Chaos Monkey',
        'Chatbot',
        'Click Network',
        'Clickprint',
        'Clicktivism',
        'Client',
        'Cloud Capitalist',
        'Cloud Computing',
        'Coaster',
        'Cocooning',
        'Code Monkey',
        'Computer Literate',
        'Computron',
        'Coning',
        'Cookie Poisoning',
        'Copypasta',
        'Corridor Warrior',
        'Counter-Googling',
        'Crowdfunding',
        'Crowdsolving',
        'Cyber Range',
        'Cyberbeggar',
        'Cybercide',
        'Dark Data',
        'Data Archaeology',
        'Data Blending',
        'Data Ninja',
        'Data Shadow',
        'Data Smog',
        'Datafication',
        'Dictionary Attack',
        'Digitization',
        'Digitize',
        'Dogfooding',
        'Doorstop',
        'Dot-Con',
        'Dotsam',
        'Dribbleware',
        'Drive-By Download',
        'Dropper',
        'Duck',
        'Dumpster Diving',
        'E-Dundant',
        'Easter Egg',
        'Echo Chamber',
        'Egosurfing',
        'Email Train',
        'Emailing While Intoxicated',
        'Emulation',
        'Enterprise Data Management',
        'Exabyte',
        'Fail',
        'Fanboy',
        'Fangirl',
        'Farming',
        'Fat-Finger Error',
        'Fauxtography',
        'Fintech',
        'Fire Fighting',
        'Flame',
        'Flash Mob',
        'Foo',
        'Foobar',
        'Future Proof',
        'Gadget Fatigue',
        'GamerGate',
        'Gibibyte',
        'Globalization',
        'Going Cloud',
        'Google+ification',
        'Greenwashing',
        'Groupthink',
        'Hack',
        'Hacker',
        'Hackerazzi',
        'Hackintosh',
        'Hakspeak',
        'Hexadecimal',
        'Hindenbug',
        'Humanware',
        'Hypermedia',
        'Ideavirus',
        'iDevice',
        'In The Wild',
        'Infocentric',
        'Initialism',
        'Intelligent Edge',
        'Interweb',
        'Jailbreak App',
        'Kibibyte',
        'Kludge',
        'Ladyphone',
        'Last Mile Technology',
        'Laymanize',
        'Lifecasting',
        'Logarithm',
        'Lurking',
        'Marketroid',
        'Master/Slave',
        'Meatware',
        'Mebibyte',
        'Microcode',
        'Murphy\'s Law',
        'Nastygram',
        'Nickelbacking',
        'Noob',
        'Open Source',
        'Operational Resilience',
        'Out of Band',
        'Pebibyte',
        'Percussive Maintenance',
        'Performant',
        'Persistent-State World',
        'Quality In, Quality Out (QIQO)',
        'Quantum Bogodynamics',
        'Rathole',
        'Real Reality',
        'Recursive Acronym',
        'Sandboxing',
        'Scatternet',
        'Script Kiddie',
        'Shareware',
        'Six Sigma',
        'Skunkworks',
        'Slacktivism',
        'Smurfing',
        'Sockpuppet',
        'Spamming',
        'Startup',
        'Tebibyte',
        'Techanista',
        'Technical Debt',
        'Terabyte',
        'TLDR',
        'Tradigital'
        'Transmedia',
        'Treeware',
        'Troll',
        'Uberveillance',
        'Vendorware',
        'Wardriving',
        'Web',
        'Wireless',
        'Xenodochial',
        'Yottabyte',
        'Zettabyte']
    return buzzwords